stash:
  image: atlassian/stash
  ports:
   - "7990:7990"
   - "7999:7999"
  volumes:
   - /root/orchestration/stash-data:/var/atlassian/application-data/stash
  links:
   - db
  user: root
  privileged: true
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: somepassword
